export const DATA_SOURCE: string = 'DATA_SOURCE';
export const USER_REPOSITORY: string = 'USER_REPOSITORY';
export const ORGANIZATIONS_REPOSITORY: string = 'ORGANIZATION_REPOSITORY';
export const ORGANIZATIONS_MEMBERS_REPOSITORY: string =
  'ORGANIZATIONS_MEMBERS_REPOSITORY';
export const PERMISSIONS_REPOSITORY: string = 'PERMISSIONS_REPOSITORY';
