name: Staging PR

on:
  pull_request:
    branches:
      - staging

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🛠 Manually Install pnpm (Avoid Corepack Issues)
      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version  # Verify installation

      # 🎯 Setup Node.js AFTER pnpm is installed
      - name: Setup Node.js with pnpm caching
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Backend Lint
        run: |
          cd avoda-be
          pnpm lint

      - name: Backend Test
        run: |
          cd avoda-be
          pnpm test

      - name: Frontend Lint & Format
        run: |
          cd avoda-fe
          pnpm lint
          pnpm format

      - name: Frontend Build
        run: |
          cd avoda-fe
          pnpm build
